### ISSUE TITLE
AttributeError: 'Namespace' object has no attribute 'quiet'

### ISSUE THREAD

**Issue by sikuan** [HadrienG/InSilicoSeq#177]
I got a strange warning maybe from /usr/bin/iss without any argument for "quiet" and "debug".

```
$ iss
usage: iss [subcommand] [options]

InSilicoSeq: A sequencing simulator

optional arguments:
  -h, --help     show this help message and exit
  -v, --version  print software version and exit

available subcommands:
  
    model        generate an error model from a bam file
    generate     simulate reads from an error model
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/bin/iss", line 8, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/iss/app.py", line 540, in main
    elif args.quiet:
AttributeError: 'Namespace' object has no attribute 'quiet'
```

**Comment by HadrienG** [comment]
Hi!

Thanks for reporting this. This is from an extra `raise` that I used for debugging and forgot to remove in the last release. It'll be fixed in `1.5.0`

Best,
/Hadrien
