### ISSUE TITLE
Using kde ErrorModel problem!

### ISSUE THREAD

**Issue by Wanli-HE** [HadrienG/InSilicoSeq#193]
hi, when i used the tested data set, the error was raised, like this! do you know was happended?

 iss generate --genomes SRS121011.fasta --model miseq --output miseq_reads

INFO:iss.app:Starting iss generate
INFO:iss.app:Using kde ErrorModel
Traceback (most recent call last):
  File "/mibi/Wanli/anaconda/envs/wanli/bin/iss", line 10, in <module>
    sys.exit(main())
  File "/mibi/Wanli/anaconda/envs/wanli/lib/python3.6/site-packages/iss/app.py", line 489, in main
    args.func(args)
  File "/mibi/Wanli/anaconda/envs/wanli/lib/python3.6/site-packages/iss/app.py", line 61, in generate_reads
    err_mod = kde.KDErrorModel(npz)
  File "/mibi/Wanli/anaconda/envs/wanli/lib/python3.6/site-packages/iss/error_models/kde.py", line 43, in __init__
    self.quality_forward = self.error_profile['quality_hist_forward']
  File "/mibi/Wanli/anaconda/envs/wanli/lib/python3.6/site-packages/numpy/lib/npyio.py", line 262, in __getitem__
    pickle_kwargs=self.pickle_kwargs)
  File "/mibi/Wanli/anaconda/envs/wanli/lib/python3.6/site-packages/numpy/lib/format.py", line 722, in read_array
    raise ValueError("Object arrays cannot be loaded when "
ValueError: Object arrays cannot be loaded when allow_pickle=False

**Comment by HadrienG** [comment]
Hi!

Could you tell me which version of both InSilicoseq and numpy you are using?

you can check numpy's version number interactively with:

```python
import numpy
print(numpy.__version__)
```
