### ISSUE TITLE
introduce_indels out of range

### ISSUE THREAD

**Issue by HadrienG** [HadrienG/InSilicoSeq#21]
The introduce_indels loop sometimes goes out of the sequence bounds

Traceback:

```
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/hadrien/Documents/github/InSilicoSeq/iss/__main__.py", line 5, in <module>
    main()
  File "/Users/hadrien/Documents/github/InSilicoSeq/iss/app.py", line 318, in main
    args.func(args)
  File "/Users/hadrien/Documents/github/InSilicoSeq/iss/app.py", line 123, in generate_reads
    generator.to_fastq(read_gen, args.output)
  File "/Users/hadrien/Documents/github/InSilicoSeq/iss/generator.py", line 125, in to_fastq
    for read_tuple in generator:
  File "/Users/hadrien/Documents/github/InSilicoSeq/iss/generator.py", line 69, in reads
    forward, 'forward', sequence, bounds)
  File "/Users/hadrien/Documents/github/InSilicoSeq/iss/error_models/__init__.py", line 172, in introduce_indels
    if mutable_seq[nucl] == 'N':
  File "/Users/hadrien/Documents/venvs/iss/lib/python3.6/site-packages/Bio/Seq.py", line 1839, in __getitem__
    return self.data[index]
IndexError: array index out of range
```

**Comment by HadrienG** [comment]
catching the exception in 8ecb2ab
