### ISSUE TITLE
Error message python: "TypeError: data should be a string, bytes, bytearray, Seq, or MutableSeq object"

### ISSUE THREAD

**Issue by Gandasegui** [HadrienG/InSilicoSeq#212]
Hello,

when trying to run iss in bioconda environment on a fasta file I always get the same error message from python:

INFO:iss.app:Starting iss generate
INFO:iss.app:Using kde ErrorModel
INFO:iss.util:Stitching input files together
INFO:iss.app:Using lognormal abundance distribution
INFO:iss.app:Using 2 cpus for read generation
INFO:iss.app:Generating 1000000 reads
INFO:iss.app:Generating reads for record: SNRZ01000001.1
/home/c.c2097288/.local/lib/python3.7/site-packages/Bio/Seq.py:1756: BiopythonDeprecationWarning: myseq.tomutable() is deprecated; please use MutableSeq(myseq) instead.
  BiopythonDeprecationWarning,
/home/c.c2097288/.local/lib/python3.7/site-packages/Bio/Seq.py:2751: BiopythonDeprecationWarning: myseq.toseq() is deprecated; please use Seq(myseq) instead.
  BiopythonDeprecationWarning,
/home/c.c2097288/.local/lib/python3.7/site-packages/Bio/Seq.py:1756: BiopythonDeprecationWarning: myseq.tomutable() is deprecated; please use MutableSeq(myseq) instead.
  BiopythonDeprecationWarning,
/home/c.c2097288/.local/lib/python3.7/site-packages/Bio/Seq.py:2751: BiopythonDeprecationWarning: myseq.toseq() is deprecated; please use Seq(myseq) instead.
  BiopythonDeprecationWarning,
joblib.externals.loky.process_executor._RemoteTraceback:
"""
Traceback (most recent call last):
  File "/home/c.c2097288/.local/lib/python3.7/site-packages/joblib/externals/loky/process_executor.py", line 431, in _process_worker
    r = call_item()
  File "/home/c.c2097288/.local/lib/python3.7/site-packages/joblib/externals/loky/process_executor.py", line 285, in __call__
    return self.fn(*self.args, **self.kwargs)
  File "/home/c.c2097288/.local/lib/python3.7/site-packages/joblib/_parallel_backends.py", line 595, in __call__
    return self.func(*args, **kwargs)
  File "/home/c.c2097288/.local/lib/python3.7/site-packages/joblib/parallel.py", line 263, in __call__
    for func, args, kwargs in self.items]
  File "/home/c.c2097288/.local/lib/python3.7/site-packages/joblib/parallel.py", line 263, in <listcomp>
    for func, args, kwargs in self.items]
  File "/home/c.c2097288/.local/lib/python3.7/site-packages/iss/generator.py", line 62, in reads
    forward, reverse = simulate_read(record, ErrorModel, i, cpu_number)
  File "/home/c.c2097288/.local/lib/python3.7/site-packages/iss/generator.py", line 139, in simulate_read
    forward, 'forward', sequence, bounds)
  File "/home/c.c2097288/.local/lib/python3.7/site-packages/iss/error_models/__init__.py", line 193, in introduce_indels
    mutable_seq, orientation, full_seq, bounds)
  File "/home/c.c2097288/.local/lib/python3.7/site-packages/iss/error_models/__init__.py", line 135, in adjust_seq_length
    nucl_to_add = str(full_sequence[read_end + i])
  File "/home/c.c2097288/.local/lib/python3.7/site-packages/Bio/Seq.py", line 433, in __getitem__
    return self.__class__(self._data[index])
  File "/home/c.c2097288/.local/lib/python3.7/site-packages/Bio/Seq.py", line 1728, in __init__
    "data should be a string, bytes, bytearray, Seq, or MutableSeq object"
TypeError: data should be a string, bytes, bytearray, Seq, or MutableSeq object
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/c.c2097288/.conda/envs/insilicoseq/bin/iss", line 10, in <module>
    sys.exit(main())
  File "/home/c.c2097288/.local/lib/python3.7/site-packages/iss/app.py", line 608, in main
    args.func(args)
  File "/home/c.c2097288/.local/lib/python3.7/site-packages/iss/app.py", line 312, in generate_reads
    args.gc_bias, mode) for i in range(cpus))
  File "/home/c.c2097288/.local/lib/python3.7/site-packages/joblib/parallel.py", line 1054, in __call__
    self.retrieve()
  File "/home/c.c2097288/.local/lib/python3.7/site-packages/joblib/parallel.py", line 933, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/home/c.c2097288/.local/lib/python3.7/site-packages/joblib/_parallel_backends.py", line 542, in wrap_future_result
    return future.result(timeout=timeout)
  File "/home/c.c2097288/.conda/envs/insilicoseq/lib/python3.7/concurrent/futures/_base.py", line 435, in result
    return self.__get_result()
  File "/home/c.c2097288/.conda/envs/insilicoseq/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
TypeError: data should be a string, bytes, bytearray, Seq, or MutableSeq object

How can I solve this? Thanks in advance.

**Comment by hirosatosd** [comment]
Try downgrading the biopython to 1.78. That worked for me

pip install biopython==1.78

**Comment by HadrienG** [comment]
I updated the bioconda recipe to require biopython <= 1.78. A minor version to fix the pip installs will follow soon

**Comment by laxMax** [comment]
Hi, I had the same issue and create a new conda enviroment to install biopython == 1.78. It turns out that it cannot work for me.

**Comment by laxMax** [comment]
> Hi, I had the same issue and create a new conda enviroment to install biopython == 1.78. It turns out that it cannot work for me.
Get this solved !
