### ISSUE TITLE
Traceback Error + Temporary File Outputs 

### ISSUE THREAD

**Issue by epanousis** [HadrienG/InSilicoSeq#219]
Hi there! 

When I try to run InSilicoSeq on my multifasta, I am getting the following error: 

Additionally, once the program errors out, I am left with hundreds of temporary FASTQs in my directory.

Any help is appreciated! 

Thanks. 
```
INFO:iss.app:Generating reads for record: Prevalence_Sequence_ID:107139|ARO_Name:mexM|ARO:3003704|Detection_Model:Protein
INFO:iss.app:Generating reads for record: Prevalence_Sequence_ID:122540|ARO_Name:OpmH|ARO:3003682|Detection_Model:Protein
INFO:iss.app:Generating reads for record: Prevalence_Sequence_ID:190619|ARO_Name:SHV-11|ARO:3001070|Detection_Model:Protein
INFO:iss.app:Generating reads for record: Prevalence_Sequence_ID:196611|ARO_Name:Mycobacterium
joblib.externals.loky.process_executor._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/panousie/.local/lib/python3.8/site-packages/joblib/externals/loky/process_executor.py", line 436, in _process_worker
    r = call_item()
  File "/home/panousie/.local/lib/python3.8/site-packages/joblib/externals/loky/process_executor.py", line 288, in __call__
    return self.fn(*self.args, **self.kwargs)
  File "/home/panousie/.local/lib/python3.8/site-packages/joblib/_parallel_backends.py", line 595, in __call__
    return self.func(*args, **kwargs)
  File "/home/panousie/.local/lib/python3.8/site-packages/joblib/parallel.py", line 262, in __call__
    return [func(*args, **kwargs)
  File "/home/panousie/.local/lib/python3.8/site-packages/joblib/parallel.py", line 262, in <listcomp>
    return [func(*args, **kwargs)
  File "/home/panousie/.local/lib/python3.8/site-packages/iss/generator.py", line 62, in reads
    forward, reverse = simulate_read(record, ErrorModel, i, cpu_number)
  File "/home/panousie/.local/lib/python3.8/site-packages/iss/generator.py", line 138, in simulate_read
    forward.seq = ErrorModel.introduce_indels(
  File "/home/panousie/.local/lib/python3.8/site-packages/iss/error_models/__init__.py", line 186, in introduce_indels
    if random.random() < deletions[position][mutable_seq[nucl].upper()]:
KeyError: '-'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/panousie/.local/bin/iss", line 8, in <module>
    sys.exit(main())
  File "/home/panousie/.local/lib/python3.8/site-packages/iss/app.py", line 608, in main
    args.func(args)
  File "/home/panousie/.local/lib/python3.8/site-packages/iss/app.py", line 306, in generate_reads
    record_file_name_list = Parallel(
  File "/home/panousie/.local/lib/python3.8/site-packages/joblib/parallel.py", line 1056, in __call__
    self.retrieve()
  File "/home/panousie/.local/lib/python3.8/site-packages/joblib/parallel.py", line 935, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/home/panousie/.local/lib/python3.8/site-packages/joblib/_parallel_backends.py", line 542, in wrap_future_result
    return future.result(timeout=timeout)
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 444, in result
    return self.__get_result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
KeyError: '-'

```

**Comment by HadrienG** [comment]
Hi!

Sorry for the (very) late reply. Could you provide me with the input fasta and command?

/Hadrien
