### ISSUE TITLE
Coverage file error

### ISSUE THREAD

**Issue by esteinig** [HadrienG/InSilicoSeq#220]
Versions:

* Python 3.9
* ISS 1.5.4

Reproduce:

```
echo -e "ref.fasta    0.1" > coverage.txt
iss generate --cpus 4 --draft ref.fasta --model miseq --coverage_file coverage.txt --output pool_miseq
```

Error:

```
INFO:iss.app:Starting iss generate
INFO:iss.app:Using kde ErrorModel
INFO:iss.util:Stitching input files together
WARNING:iss.app:--coverage_file is an experimental feature
WARNING:iss.app:--coverage_file disables --n_reads
INFO:iss.app:Using coverage file:coverage.txt
Traceback (most recent call last):
  File "/data/opt/conda/envs/iss/bin/iss", line 10, in <module>
    sys.exit(main())
  File "/data/opt/conda/envs/iss/lib/python3.9/site-packages/iss/app.py", line 608, in main
    args.func(args)
  File "/data/opt/conda/envs/iss/lib/python3.9/site-packages/iss/app.py", line 174, in generate_reads
    abundance_dic_short,
UnboundLocalError: local variable 'abundance_dic_short' referenced before assignment
```

**Comment by amckay1** [comment]
Ran into this as well
