### ISSUE TITLE
Traceback Error + Missing Temporary Fastq File 

### ISSUE THREAD

**Issue by ReginaEsinamAbotsi** [HadrienG/InSilicoSeq#264]
Hello,

Thank you so much for developing this awesome tool!

I am trying to simulate reads by running this script on hpc but kept getting the error below. I thought it was a resource issue so I increased the cpu and memory but still no luck. Any ideas how to resolve this?

> cat << EOF > sepi1M.sh
#!/usr/bin/bash
source /data/abotsire/conda/etc/profile.d/conda.sh
conda activate insilicoseq_env
cd /data/abotsire/insilicoseq/workingdocs/sepi1M
iss generate --cpus 16 --n_reads 1000000 --draft ../ALL.draft.sepi/*.fna -g ../ALL.complete/*.fna --abundance_file ../abundance_file_FINALsepi.txt --model novaseq --output sepi1M
conda deactivate
EOF

> sbatch --cpus-per-task=16 --mem=150g --time=4:00:00 sepi1M.sh

The error is 

> INFO:iss.app:Starting iss generate
INFO:iss.generator:Using kde ErrorModel
INFO:iss.util:Stitching input files together
INFO:iss.generator:Using abundance file:../abundance_file_FINALsepi.txt
INFO:iss.app:Using 16 cpus for read generation
INFO:iss.app:Generating 1000000 reads
INFO:iss.util:Stitching input files together
Traceback (most recent call last):
  File "/gpfs/gsfs12/users/abotsire/conda/envs/insilicoseq_env/bin/iss", line 10, in <module>
    sys.exit(main())
  File "/gpfs/gsfs12/users/abotsire/conda/envs/insilicoseq_env/lib/python3.10/site-packages/iss/app.py", line 454, in main
    args.func(args)
  File "/gpfs/gsfs12/users/abotsire/conda/envs/insilicoseq_env/lib/python3.10/site-packages/iss/app.py", line 126, in generate_reads
    util.concatenate(temp_R1, args.output + "_R1.fastq")
  File "/gpfs/gsfs12/users/abotsire/conda/envs/insilicoseq_env/lib/python3.10/site-packages/iss/util.py", line 233, in concatenate
    with open(file_name, "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'sepi1M.iss.tmp.13_R1.fastq'

Thank you so much!

**Comment by ReginaEsinamAbotsi** [comment]
Solved, thanks!
