### ISSUE TITLE
Bug if no number of reads is specified

### ISSUE THREAD

**Issue by jhayer** [HadrienG/InSilicoSeq#40]
If we use the default number of reads and do not specify any, we get this:
Traceback (most recent call last):
  File "/usr/local/bin/iss", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/iss/app.py", line 365, in main
    args.func(args)
  File "/usr/local/lib/python3.6/site-packages/iss/app.py", line 108, in generate_reads
    n_reads = util.convert_n_reads(args.n_reads)
  File "/usr/local/lib/python3.6/site-packages/iss/util.py", line 121, in convert_n_reads
    if unit[-1].isdigit():
TypeError: 'int' object is not subscriptable

**Comment by HadrienG** [comment]
addressed with #7ea66e4

thanks for contributing 🚀 🎉
