### ISSUE TITLE
the other side has unexpectedly closed connection

### ISSUE THREAD

**Issue by HadrienG** [HadrienG/InSilicoSeq#77]
the download module sometimes fails because the NCBI unexpectedly closes the connection (kicks us out?). 

We should catch that exception and retry

**Comment by HadrienG** [comment]
Traceback:

```pytb
Traceback (most recent call last):
  File "/Users/hadrien/.local/share/virtualenvs/InSilicoSeq-sVXyRzi0/lib/python3.7/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/Users/hadrien/Documents/github/InSilicoSeq/iss/test/test_download.py", line 24, in test_ncbi
    genome_list = download.ncbi('bacteria', 2)
  File "/Users/hadrien/Documents/github/InSilicoSeq/iss/download.py", line 38, in ncbi
    id=ident))[0]['LinkSetDb'][0]['Link'][0]['Id']
  File "/Users/hadrien/.local/share/virtualenvs/InSilicoSeq-sVXyRzi0/lib/python3.7/site-packages/Bio/Entrez/__init__.py", line 458, in read
    record = handler.read(handle)
  File "/Users/hadrien/.local/share/virtualenvs/InSilicoSeq-sVXyRzi0/lib/python3.7/site-packages/Bio/Entrez/Parser.py", line 362, in read
    self.parser.ParseFile(handle)
  File "/opt/concourse/worker/volumes/live/8dbdbf04-8ad9-4e8a-6a2e-2f6cab8ea7e7/volume/python_1530186999843/work/Modules/pyexpat.c", line 466, in EndElement
  File "/Users/hadrien/.local/share/virtualenvs/InSilicoSeq-sVXyRzi0/lib/python3.7/site-packages/Bio/Entrez/Parser.py", line 500, in endElementHandler
    value = consumer.value
  File "/Users/hadrien/.local/share/virtualenvs/InSilicoSeq-sVXyRzi0/lib/python3.7/site-packages/Bio/Entrez/Parser.py", line 182, in value
    raise RuntimeError(value)
RuntimeError: NCBI C++ Exception:
    Error: TXCLIENT(CException::eUnknown) "/pubmed_gen/rbuild/version/20180312/entrez/2.14.2/src/internal/txclient/TxClient.cpp", line 1038: ncbi::CTxRawClientImpl::readAll() --- Read failed: EOF (the other side has unexpectedly closed connection), peer: 130.14.22.29:8064
```
