### ISSUE TITLE
Older versions of numpy cause error

### ISSUE THREAD

**Issue by lowandrew** [HadrienG/InSilicoSeq#86]
It looks like numpy >1.16 required for the package to work - when I tried after installing via `pip` with python 3.7.1:
`iss generate --draft /path/to/draft.fasta --model miseq --output test_reads` with numpy 1.15.4 installed, I get the following error:

```
Traceback (most recent call last):
  File "__init__.pxd", line 1036, in numpy.import_array
RuntimeError: module compiled against API version 0xc but this version of numpy is 0xa

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lowa/miniconda3/bin/iss", line 7, in <module>
    from iss.app import main
  File "/home/lowa/miniconda3/lib/python3.7/site-packages/iss/app.py", line 4, in <module>
    from iss import bam
  File "/home/lowa/miniconda3/lib/python3.7/site-packages/iss/bam.py", line 8, in <module>
    from iss import modeller
  File "/home/lowa/miniconda3/lib/python3.7/site-packages/iss/modeller.py", line 8, in <module>
    from scipy import stats
  File "/home/lowa/miniconda3/lib/python3.7/site-packages/scipy/stats/__init__.py", line 367, in <module>
    from .stats import *
  File "/home/lowa/miniconda3/lib/python3.7/site-packages/scipy/stats/stats.py", line 172, in <module>
    import scipy.special as special
  File "/home/lowa/miniconda3/lib/python3.7/site-packages/scipy/special/__init__.py", line 641, in <module>
    from ._ufuncs import *
  File "_ufuncs.pyx", line 1, in init scipy.special._ufuncs
  File "_ufuncs_extra_code_common.pxi", line 34, in init scipy.special._ufuncs_cxx
  File "__init__.pxd", line 1038, in numpy.import_array
ImportError: numpy.core.multiarray failed to import
```

Upgrading numpy to 1.16.1 resolves the issue - maybe specify a minimum version in `setup.py`?

**Comment by HadrienG** [comment]
Hi!

I successfully tested `iss` in a virtualenv with the following dependencies:

- python 3.7
- numpy 1.1.5.4
- scipy 1.2.1

If you give me your numpy version I can try to replicate one more time, but unfortunately I think the problem came from a broken numpy install on your side.

Best,
Hadrien

**Comment by lowandrew** [comment]
I can't seem to reproduce the issue now - I think you're right, I must have had a broken install of numpy cached that got used when installing. I can verify that `iss` is working with python 3.7, numpy 1.15.4, and scipy 1.2.1.

Thanks for looking into this!
